### ISSUE TITLE
Could you please release the test data

### ISSUE THREAD

**Issue by FearAlwaysWorks** [Nealcly/templateNER#12]
Hi, Thank you for your nice work. 
Could you please release the test data of this code?
I have no idea what format of the data should be applied in inference.py.

**Comment by Nealcly** [comment]
Hi, the format of the test data is one sentence to be annotated per line.

**Comment by FearAlwaysWorks** [comment]
yo~我是王晓也，我已经收到你的邮件了，我会尽快查看的，如果需要我的回复，请您耐心哟~

**Comment by aso538** [comment]
您好 请问可以给个示例嘛 第一个单词是固定要实体嘛

**Comment by FearAlwaysWorks** [comment]
yo~我是王晓也，我已经收到你的邮件了，我会尽快查看的，如果需要我的回复，请您耐心哟~

**Comment by Nealcly** [comment]
> 您好 请问可以给个示例嘛 第一个单词是固定要实体嘛

就是给要标注数据的纯文本
