### ISSUE TITLE
Error encountered when running the inference.py file

### ISSUE THREAD

**Issue by ConnieTong** [Nealcly/templateNER#9]
Hi,
Thank you for sharing. Could you please provide the version of transformers and other packages?  I encountered the problem when running the inference.py  (Line: output = model(input_ids=input_ids.to(device), decoder_input_ids=output_ids[:, :output_ids.shape[1] - 2].to(device))[0).
The error is as below:

![1640094724(1)](https://user-images.githubusercontent.com/10631077/146941206-16692204-1d3a-4f30-aa0b-ecd1dcb7479e.png)

**Comment by fireindark707** [comment]
Hello, Have you solved the problem? I encountered the same one.

**Comment by qhq123** [comment]
I encountered the question too . Could you please tell me the solution about it?THANKS!
